global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "fastapi_model"
    metrics_path: /metrics
    static_configs:
      - targets: ["localhost:8000"]

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
